config/routes.rb
Rails.application.routes.draw do


  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  root 'posts#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:show, :index, :edit, :update, :destroy] do
  	resources :relationships, only: [:create, :destroy]
  	get :follows, on: :member
  	get :followers, on: :member
  end
  get 'users/:id/likes' =>'users#likes', as: 'user_likes'

  resources :posts do
  	resources :likes, only: [:create, :destroy]
  	resources :comments, only: [:create, :destroy]
  end
  get 'posts/:id/ranks' =>'posts#rank', as: 'post_rank'
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy

  has_many :active_relationships, class_name: "Relationship", foreign_key: :following_id
  has_many :followings, through: :active_relationships, source: :follower

  has_many :passive_relationships, class_name: "Relationship", foreign_key: :follower_id
  has_many :followers, through: :passive_relationships, source: :following

  attachment :profile_image, type: :image

  validates :name, presence: true, length: { in: 2..20 }
  validates :email, presence: true, uniqueness: true
  validates :introduction, length: { maximum: 120 }


#フォロー済みかどうか判定するメソッド
  def followed_by?(user)
  	passive_relationships.find_by(following_id: user.id).present?
  	# 自分がフォローしようとしているユーザーがフォローされているユーザーの中から、引数に渡されたユーザー(自分)がいるかどうかを調べる
  end


#ユーザーに紐づいたpostインスタンスを戻り値として返すメソッド
  def posts
  	return Post.where(user_id: self.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!

  def index
    # @users = User.page(params[:page]).reverse_order
    @user_search = User.ransack(params[:q])
    @search_users = @user_search.result.page(params[:page]).reverse_order
  end

  def show
  	@user = User.find(params[:id])
    @user_follows = @user.followings
    @user_followers = @user.followers
  end

  def edit
    @user = User.find(params[:id])
    if current_user != @user
    flash[:alert] = "編集権限がありません"
    redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "ユーザー情報を編集しました"
      redirect_to user_path(@user)
    else
      flash[:alert] = "編集に失敗しました"
      redirect_to user_path(@user)
    end
  end

  def destroy
    user = current_user
    user.destroy
    redirect_to root_path
  end

  def likes
    @user = User.find(params[:id])
    @likes = Like.where(user_id: @user.id)
    @user_follows = @user.followings
    @user_followers = @user.followers
  end

  def follows
    user = User.find(params[:id])
    @users = user.followings
  end

  def followers
    user = User.find(params[:id])
    @users = user.followers
  end


private
  def user_params
    params.require(:user).permit(:name, :email, :profile_image, :introduction)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_mypage.html.erb
<div class="container">
	<div class="card pl-5 pr-3 my-5 mx-5 pt-3 bg-light">
		<div class="row mt-5">
			<div class="col-3">
				<p><%= attachment_image_tag user, :profile_image, :fill, 200, 190, fallback: "no-image-user.png", size: '200x190', class: "img-fluid" %></p>
			</div>
			<div class="col-2">
				<h2 class="text-nowrap"><%= user.name %></h2>
				<% if user == current_user %>
					<p class="text-nowrap"><%= user.email %></p>
					<p><%= link_to "編集する", edit_user_path(user), class: "btn btn-dark text-nowrap" %></p>
					<p><%= link_to "退会する", user_path(user), method: :delete, data: { confirm: '本当に退会してよろしいですか？', cancel: 'やめる', commit: '退会する'}, title: '確認', class: "btn btn-danger my-3 text-nowrap" %></p>
				<% else %>
					<% if user.followed_by?(current_user) %>
						<%= link_to "フォロー解除", user_relationship_path(user), method: :delete, class: "btn btn-outline-primary" %>
					<% else %>
						<%= link_to "フォロー", user_relationships_path(user), method: :post, class: "btn btn-outline-primary" %>
					<% end %>
				<% end %>
			</div>

app/views/users/edit.html.erb
<div class="d-flex justify-content-center mt-5">
	<div class="card text-dark w-50 m-auto">
		<div class="card-header bg-info text-center text-white">
			ユーザー情報編集
		</div>

		<div class="card-body bg-light" >
			<div class="form-group">
				<%= form_with model: @user do |f| %>
					<%= f.label :名前 %>
					<%= f.text_field :name, class: "form-control w-50" %>
					<%= f.label :メールアドレス %>
					<%= f.text_field :email, class: "form-control w-75" %>
					<%= f.attachment_field :profile_image, placeholder:"プロフィール画像", class: "form-control-file my-3" %>
					<%= f.label :自己紹介 %>
					<%= f.text_area :introduction, class: "form-control" %>
					<%= f.submit "登録", class: "btn btn-dark my-3" %>
				<% end %>
			</div>
		</div>
	</div>
</div>

app/views/users/followers.html.erb
<div class="d-flex justify-content-center">
	<div class="card pl-5 pr-3 my-5 mx-5 pt-3 bg-light">
		<% if @users.present? %>
			<div class="card-header bg-info text-center text-white">
				フォロワー
			</div>
				<table class="table table-striped">
					<tbody>
						<% @users.each do |user| %>
						<tr>
							<td><%= attachment_image_tag user, :profile_image, :fill, 50, 50, fallback: "no-image-user.png", size: '50x50' %></td>
							<td><%= link_to user.name, user_path(user) %></td>
							<% if user != current_user %>
								<% if user.followed_by?(current_user) %>
									<td><%= link_to "フォロー解除", user_relationship_path(user.id), method: :delete, class: "btn btn-outline-primary " %></td>
								<% else %>
									<td><%= link_to "フォロー", user_relationships_path(user.id), method: :post, class: "btn btn-outline-primary" %></td>
								<% end %>
							<% end %>
							<td><%= user.introduction.truncate(25, omission:'...') %></td>
						</tr>
						<% end %>
					</tbody>
				</table>
		<% else %>
			<h1>フォロワーがいません</h1>
		<% end %>
	</div>
</div>

app/views/users/follows.html.erb
<div class="d-flex justify-content-center">
	<div class="card pl-5 pr-3 my-5 mx-5 pt-3 bg-light">
		<% if @users.present? %>
			<div class="card-header bg-info text-center text-white">
				フォロー中
			</div>
				<table class="table table-striped">
					<tbody>
						<% @users.each do |user| %>
						<tr>
							<td><%= attachment_image_tag user, :profile_image, :fill, 50, 50, fallback: "no-image-user.png", size: '50x50' %></td>
							<td><%= link_to user.name, user_path(user) %></td>
							<% if user != current_user %>
								<% if user.followed_by?(current_user) %>
									<td><%= link_to "フォロー解除", user_relationship_path(user.id), method: :delete, class: "btn btn-outline-primary " %></td>
								<% else %>
									<td><%= link_to "フォロー", user_relationships_path(user.id), method: :post, class: "btn btn-outline-primary" %></td>
								<% end %>
							<% end %>
							<td><%= user.introduction.truncate(25, omission:'...') %></td>
						</tr>
						<% end %>
					</tbody>
				</table>
		<% else %>
			<h1>まだ誰もフォローしていません</h1>
		<% end %>
	</div>
</div>

app/views/users/index.html.erb
<div class="container">
	<div class="searchbox mt-3">
		<%= search_form_for @user_search , url: users_path do |f| %>
			<%= f.text_field :name_cont, placeholder: "ユーザーを検索..." %>
			<%= f.submit "検索", class: 'btn btn-light btn-sm' %>
		<% end %>
	</div>

	<div class="d-flex justify-content-center">
		<div class="card pl-3 pr-3 my-5 mx-5 pt-3 bg-light">
			<table class="table table-striped">
				<tbody>
					<% @search_users.each do |user| %>
					<tr>
						<td><%= attachment_image_tag user, :profile_image, :fill, 50, 50, fallback: "no-image-user.png", size: '50x50' %></td>
						<td><%= link_to user.name, user_path(user) %></td>
						<% if user != current_user %>
							<% if user.followed_by?(current_user) %>
								<td width="25%"><%= link_to "フォロー解除", user_relationship_path(user, Relationship.find_by(follower_id: user.id, following_id: current_user.id)), method: :delete, class: "btn btn-outline-primary " %></td>
							<% else %>
								<td width="25%"><%= link_to "フォロー", user_relationships_path(user.id), method: :post, class: "btn btn-outline-primary" %></td>
							<% end %>
						<% else %>
							<td>ログイン中</td>
						<% end %>
						<td><%= truncate(user.introduction,length:25, omission:'...')%></td>
					</tr>
					<% end %>
				</tbody>
			</table>
		</div>
	</div>
	<div class="d-flex justify-content-end">
		<%=paginate @search_users, class: "paginate" %>
	</div>
</div>

app/views/users/likes.html.erb
<%= render 'users/mypage', user: @user  %>

		<div class="col-sm-8 col-md-8 col-lg-6">
			<table class="table table-borderless text-center">
				<thead>
					<tr>
						<th>投稿</th>
						<th></th>
						<th>フォロー</th>
						<th>フォロワー</th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td class="user-count"><%= @user.posts.count %></td>
						<td></td>
						<td class="user-count">
							<%= link_to follows_user_path(@user) do %>
							<%= @user_follows.count %>
							<% end %>
						</td>
						<td class="user-count">
							<%= link_to followers_user_path(@user) do %>
							<%= @user_followers.count %>
							<% end %>
						</td>
					</tr>
				</tbody>
			</table>
		</div>
		</div>
		<div class="balloon-top">
			<%= @user.introduction %>
		</div>
		<div class="card mr-3">
			<div class="card-header">
				<ul class="nav nav-tabs card-header-tabs d-flex justify-content-around">
					<li class="nav-item">
						<%= link_to "投稿", user_path(@user), class: "nav-link" %>
					</li>
					<li class="nav-item">
						<%= link_to "いいねした投稿", user_likes_path(@user), class: "nav-link active" %>
					</li>
				</ul>
			</div>
			<div class="row">
			<% @likes.each do |like| %>
			<% post = Post.find_by(id: like.post.id) %>
				<div class="card-center card-body col-md-4">
					<div class="card">
						<div class="card-header">
						投稿者: <%= link_to post.user.name, user_path(@user) %>
						</div>
						<div class="card-body">
							<div class="post_title text-nowrap">
								<%= post.title %>
							</div>
							<div>
								<%= link_to post_path(post) do %>
								<%= attachment_image_tag post, :image, :fill, 200, 200, class: "img-fluid" %>
								<% end %>
							</div>
						</div>
						<% if post.catname.present? %>
						  <span class="bg bg-success text-white" ><%= post.catname %></span>
						<% end %>
					</div>
				</div>
			<% end %>
			</div>
		</div>
	</div>
</div>

app/views/users/show.html.erb
<%= render 'users/mypage', user: @user  %>
	<div class="col-sm-8 col-md-8 col-lg-6">
		<table class="table table-borderless text-center">
			<thead>
				<tr>
					<th>投稿</th>
					<th></th>
					<th>フォロー</th>
					<th>フォロワー</th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<td class="user-count"><%= @user.posts.count %></td>
					<td></td>
					<td class="user-count">
						<%= link_to follows_user_path(@user) do %>
						<%= @user_follows.count %>
						<% end %>
					</td>
					<td class="user-count">
						<%= link_to followers_user_path(@user) do %>
						<%= @user_followers.count %>
						<% end %>
					</td>
				</tr>
			</tbody>
		</table>
	</div>
</div>
		<div class="balloon-top">
			<%= @user.introduction %>
		</div>

		<div class="card mr-3">
			<div class="card-header">
				<ul class="nav nav-tabs card-header-tabs d-flex justify-content-around">
					<li class="nav-item">
						<%= link_to "投稿", user_path(@user), class: "nav-link active" %>
					</li>
					<li class="nav-item">
						<%= link_to "いいねした投稿", user_likes_path(@user), class: "nav-link" %>
					</li>
				</ul>
			</div>
		<div class="row">
			<% @user.posts.each do |post| %>
				<div class="card-center card-body col-md-4">
					<div class="card">
						<div class="card-header">
							投稿者: <%= link_to post.user.name, user_path(@user) %>
						</div>
						<div class="card-body">
							<div class="post_title">
								<%= post.title %>
							</div>
							<div>
								<%= link_to post_path(post) do %>
								<%= attachment_image_tag post, :image, :fill, 200, 200, class: "img-fluid" %>
								<% end %>
							</div>
						</div>
							<% if post.catname.present? %>
							  <span class="bg bg-success text-white" ><%= post.catname %></span>
							<% end %>
					</div>
				</div>
			<% end %>
		</div>
	</div>
</div>