config/routes.rb
Rails.application.routes.draw do


  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  root 'posts#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:show, :index, :edit, :update, :destroy] do
  	resources :relationships, only: [:create, :destroy]
  	get :follows, on: :member
  	get :followers, on: :member
  end
  get 'users/:id/likes' =>'users#likes', as: 'user_likes'

  resources :posts do
  	resources :likes, only: [:create, :destroy]
  	resources :comments, only: [:create, :destroy]
  end
  get 'posts/:id/ranks' =>'posts#rank', as: 'post_rank'
  
end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :user
	has_many   :likes, dependent: :destroy
	has_many   :comments, dependent: :destroy
	validates  :title,
				presence: true,
				length: { maximum: 20 }
	validates  :body,
				length: { maximum: 120 }
	validates  :image,
				presence: true
	attachment :image, type: :image

    #いいね済みか判定するメソッド
	def liked_by?(user)
		Like.where(user_id: user.id, post_id: id) #user_idとpost_idが一致するlikeを検索する
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	before_action :authenticate_user!, except: [:index]

  def new
  	@post = Post.new
  end


  def create
  	@post = Post.new(post_params)
  	@post.user_id = current_user.id
	if @post.save
	   redirect_to root_path
	   flash[:notice] = "投稿されました"
	else
		flash.now[:alert] = "投稿に失敗しました"
		render :new
	end
  end


  def show
  	@post = Post.find(params[:id])
  	@comment = Comment.new
  end


  def index
  	@posts = Post.page(params[:page]).reverse_order
  	@rank = Post.find(Like.group(:post_id).order('count(post_id) desc').limit(3).pluck(:post_id))
  end


  def edit
  	@post = Post.find(params[:id])
  	if current_user != @post.user
  	flash[:alert] = "編集権限がありません"
    redirect_to posts_path
	end
  end


  def update
  	@post = Post.find(params[:id])
  	if @post.update(post_params)
  		flash[:notice] = "投稿内容を編集しました"
  		redirect_to post_path(@post)
  	else
  		flash.now[:alert] = "編集に失敗しました"
  		render :edit
  	end
  end


  def destroy
  	@post = Post.find(params[:id])
  	if @post.user = current_user
  		flash[:notice] = "投稿を削除しました" if @post.destroy
  	else
  		flash[:alert] = "削除に失敗しました"
  	end
  		redirect_to root_path
  end


  private

  	def post_params
  		params.require(:post).permit(:title, :body, :genre, :catname, :image)
  	end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_rank.html.erb
<div class="d-flex flex-column">
	<div class="fas fa-crown my-gold fa-5x mb-3 mr-auto"></div>
	<% ranks.each.with_index(1) do |rank, i| %>
	<h2 class="bg bg-info text-muted mr-3 text-center w-50"><%= "#{i}位" %></h1>
		<div class="card mb-2">
			<div class="card-header">
				投稿者: <%= link_to rank.user.name, user_path(rank.user) %>
			</div>
			<div class="card-body">
				<div class="d-flex justify-content-between">
					<div class="post_title"><%= rank.title %></div>
					<div><i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>いいね<%= rank.likes.count %>件</div>
				</div>

				<%= link_to post_path(rank) do %>
					<%= attachment_image_tag rank, :image, :fill, 200, 200, class: "img-fluid" %>
				<% end %>
				<% if rank.catname.present? %>
					<p><span class="bg bg-success text-white"><%= rank.catname %></span></p>
				<% end %>
			</div>
		</div>
	<% end %>
</div>

app/views/posts/edit.html.erb
<div class="d-flex justify-content-center mt-5 ">
	<div class="card text-dark w-75 ">
		<div class="card-header text-center text-white edit-post-header">
			投稿内容編集
		</div>

		<div class="card-body bg-light" >
			<div class="form-group">
				<%= form_with model: @post, local: true do |f| %>
				<%= render 'layouts/error_messages', model: f.object %>
					<div class="form-row">
						<div class="col-md-7">
							<%= f.label :タイトル %>
							<%= f.text_field :title, class: "form-control w-75" %>
						</div>
						<div class="col-md-5">
							<%= f.label :猫のお名前 %>
							<%= f.text_field :catname, class: "form-control w-75" %>
						</div>
					</div>
						<%= f.label :本文 %>
						<%= f.text_field :body, class: "form-control w-75" %>
							<%= f.attachment_field :image, class: "form-control-file my-3" %>
						<%= f.submit "更新", class: "btn btn-dark my-3" %>
						<%= link_to "削除", post_path(@post), method: :delete, data: { confirm: '本当に削除してよろしいですか？', cancel: 'やめる', commit: '削除する'}, title: '確認', class: "btn btn-danger my-3" %>
					<% end %>
			</div>
		</div>
	</div>
</div>

app/views/posts/index.html.erb
<div class="jumbotron">
	<h1 class="display-4">ようこそnekozeへ</h1>
	<p class="lead">あなたの大切な猫や街で見かけた猫を撮影してみんなで共有しよう</p>
</div>

<div class="container">
	<% if @q.present? %>
		<h5 class="search-content bg bg-light"><%= @search.title_or_catname_cont %> : の検索結果</h5>
		<h5 class="search-count bg bg-light"><%= @search_posts.total_count %>件</h5>
	<% end %>
			<div class= "row">
				 <div class="col-sm-4 col-md-3">
					<%= render 'posts/rank', ranks: @rank  %>
				</div>

				<div class="col-sm-8 col-md-9">
					<br>
					<br>
					<br>
					<br>
					<div class= "row">

						<% @search_posts.each do |post| %>
							<div class="col-sm-6 col-md-5 col-lg-4">
								<div class="card mb-3">
									<div class="card-header">
										投稿者: <%= link_to post.user.name, user_path(post.user) %>
									</div>

									<div class="card-body">
										<p><%= post.title %></p>
										<%= link_to post_path(post) do %>
											<%= attachment_image_tag post, :image, :fill, 200, 200, class: "img-fluid" %>
										<% end %>
										<% if post.catname.present? %>
										<p><span class="bg bg-success text-white" ><%= post.catname %></span></p>
										<% end %>
									</div>
								</div>
							</div>
						<% end %>
					</div>
				</div>
			</div>
			<div class="d-flex justify-content-end">
			<%=paginate @posts, class: "paginate" %>
			</div>
</div>

app/views/posts/new.html.erb
<div class="d-flex justify-content-center mt-5">
	<div class="card text-dark w-75">
		<div class="card-header text-center text-white new-post-header">
			新規投稿
		</div>

		<div class="card-body bg-light" >
			<%= form_with model: @post, local: true do |f| %>
			<%= render 'layouts/error_messages', model: f.object %>
				<div class="form-group">
					<div class="form-row">
						<div class="col-md-7">
							<%= f.label :タイトル %>
							<%= f.text_field :title, class: "form-control w-75" %>
						</div>
						<div class="col-md-5">
							<%= f.label :猫のお名前 %>
							<%= f.text_field :catname, class: "form-control w-75" %>
						</div>
					</div>
						<%= f.label :本文 %>
						<%= f.text_field :body, class: "form-control" %>
							<%= f.attachment_field :image, class: "form-control-file my-3" %>
						<%= f.submit "投稿", class: "btn btn-dark my-3" %>
					<% end %>
				</div>
		</div>
	</div>
</div>

app/views/posts/show.html.erb
<div class="d-flex justify-content-center">
	<div class="card pl-5 pr-3 my-5 mx-5 pt-3 bg-light w-75">
		<div class="row ">
			<div class="col-sm-6 col-md-6 col-lg-6">
				<div class= "d-flex flex-row">
					<h1><%= @post.title %></h1>
					<% if @post.catname.present? %>
					<p class="align-self-center mx-auto bg bg-success text-white "><strong><%= @post.catname %></p></strong>
					<% end %>
				</div>
			</div>
			<div class="col-sm-8 col-md-8 col-lg-6 border-bottom ">
				<div class= "d-flex flex-row">
					<%= link_to user_path(@post.user) do %>
						<h2 class="mx-auto text-nowrap "><%= attachment_image_tag @post.user, :profile_image, :fill, 50, 50, class: "img-fluid" %>
						<%= @post.user.name %></h2>
					<% end %>
					<% if @post.user != current_user %>
						<% if @post.user.followed_by?(current_user) %>
							<%= link_to "フォロー解除", user_relationship_path(@post.user), method: :delete, class: "btn btn-outline-primary w-50 mx-auto align-self-center" %>
						<% else %>
							<%= link_to "フォロー", user_relationships_path(@post.user), method: :post, class: "btn btn-outline-primary w-50 mx-auto align-self-center" %>
						<% end %>
					<% else %>
						<%= link_to "編集", edit_post_path(@post), class: "btn btn-outline-dark w-50 mx-auto align-self-center" %>
					<% end %>
				</div>
			</div>
		</div>
		<div class="row ">
			<div class= "col-sm-6 col-md-6 col-lg-6">
				<%= attachment_image_tag @post, :image, :fill, 600, 450, class: "img-fluid mb-3" %>
			</div>
			<div class="col-sm-8 col-md-8 col-lg-6">
				<p class="border-bottom"><%= @post.body %></p>
				<% @post.comments.each do |comment| %>
						<p><%= comment.user.name %>
						<%= comment.created_at.strftime('%Y/%m/%d') %>
						<%= comment.comment %>
					<% if comment.user == current_user %>
						<%= link_to post_comment_path(@post, comment),method: :delete do %>
							<i class="fas fa-times-circle" style="color: red"></i></p>
						<% end %>
					<% end %>
				<% end %>
			</div>
		</div>
		<div class="row">
			<div class="col-md-12">
				<% if @post.liked_by?(current_user).present? %>
					<%= link_to post_like_path(@post), method: :delete do %>
						<i class="fa fa-heart fa-2x" aria-hidden="true" style="color: red;"></i>
						<span class="like-count text-nowrap"><%= @post.likes.count %> いいね</span>
					<% end %>
				<% else %>
					<%= link_to post_likes_path(@post), method: :post do %>
						<i class="fa fa-heart-0" aria-hidden="true" ></i>
						<span class="like-count text-nowrap"><%= @post.likes.count %> いいね</span>
					<% end %>
				<% end %>
			</div>
		</div>
		<div class="row">
			<div class="col-md-12">
				<%= form_for [@post, @comment], local: true do |f| %>
					<%= f.text_area :comment, class: "form-control w-75 mt-3", placeholder: "コメントを入力" %>
					<%= f.submit "送信する", class: "btn btn-outline-dark w-50 my-3" %>
				<% end %>
			</div>
		</div>
	</div>
</div>