config/routes.rb
Rails.application.routes.draw do


  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  root 'posts#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:show, :index, :edit, :update, :destroy] do
  	resources :relationships, only: [:create, :destroy]
  	get :follows, on: :member
  	get :followers, on: :member
  end
  get 'users/:id/likes' =>'users#likes', as: 'user_likes'

  resources :posts do
  	resources :likes, only: [:create, :destroy]
  	resources :comments, only: [:create, :destroy]
  end
  get 'posts/:id/ranks' =>'posts#rank', as: 'post_rank'
  
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :user
	belongs_to :post
	validates :comment, presence: true, length: { maximum: 50 }
	default_scope -> { order(created_at: :desc) }
end

app/models/like.rb
class Like < ApplicationRecord
	belongs_to :user
	belongs_to :post
	validates :user_id, presence: true
	validates :post_id, presence: true
end

app/models/message.rb
class Message < ApplicationRecord
  # belongs_to :to_user, class_name: "User"
  # belongs_to :from_user, class_name: "User"
end

app/models/photo.rb
class Photo < ApplicationRecord

	#belongs_to :post
	# attachment :image

	# validates :image, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :user
	has_many   :likes, dependent: :destroy
	has_many   :comments, dependent: :destroy
	validates  :title,
				presence: true,
				length: { maximum: 20 }
	validates  :body,
				length: { maximum: 120 }
	validates  :image,
				presence: true
	attachment :image, type: :image

    #いいね済みか判定するメソッド
	def liked_by?(user)
		Like.where(user_id: user.id, post_id: id) #user_idとpost_idが一致するlikeを検索する
	end
end

app/models/relationship.rb
class Relationship < ApplicationRecord

	belongs_to :following, class_name: "User"
	belongs_to :follower, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy

  has_many :active_relationships, class_name: "Relationship", foreign_key: :following_id
  has_many :followings, through: :active_relationships, source: :follower

  has_many :passive_relationships, class_name: "Relationship", foreign_key: :follower_id
  has_many :followers, through: :passive_relationships, source: :following

  attachment :profile_image, type: :image

  validates :name, presence: true, length: { in: 2..20 }
  validates :email, presence: true, uniqueness: true
  validates :introduction, length: { maximum: 120 }


#フォロー済みかどうか判定するメソッド
  def followed_by?(user)
  	passive_relationships.find_by(following_id: user.id).present?
  	# 自分がフォローしようとしているユーザーがフォローされているユーザーの中から、引数に渡されたユーザー(自分)がいるかどうかを調べる
  end


#ユーザーに紐づいたpostインスタンスを戻り値として返すメソッド
  def posts
  	return Post.where(user_id: self.id)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	before_action :authenticate_user!

	def create
		post = Post.find(params[:post_id])
	    comment = current_user.comments.new(comment_params)
	    comment.post_id = post.id
	    if comment.save
	    	flash[:notice] = "コメントしました"
	    	redirect_to post_path(post)
	    else
	    	flash[:alert] = "コメントに失敗しました"
	    	redirect_to post_path(post)
		end
	end

	def destroy
		post = Post.find(params[:post_id])
		comment = current_user.comments.find(params[:id])
		comment.post_id = post.id
		comment.destroy
		redirect_to post_path(post)
	end


	private

	def comment_params
		params.require(:comment).permit(:user_id, :post_id, :comment)
	end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

	before_action :authenticate_user!

	def create
		post = Post.find(params[:post_id])
	  	like = current_user.likes.build(like_params)
	  	like.save
	  	redirect_to post_path(post)
	end

	def destroy
		post = Post.find(params[:post_id])
	  	like = current_user.likes.find_by(like_params)
	  	like.destroy
	  	redirect_to post_path(post)
	end


private

	def like_params
		params.permit(:post_id)
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	before_action :authenticate_user!, except: [:index]

  def new
  	@post = Post.new
  end


  def create
  	@post = Post.new(post_params)
  	@post.user_id = current_user.id
	if @post.save
	   redirect_to root_path
	   flash[:notice] = "投稿されました"
	else
		flash.now[:alert] = "投稿に失敗しました"
		render :new
	end
  end


  def show
  	@post = Post.find(params[:id])
  	@comment = Comment.new
  end


  def index
  	@posts = Post.page(params[:page]).reverse_order
  	@rank = Post.find(Like.group(:post_id).order('count(post_id) desc').limit(3).pluck(:post_id))
  end


  def edit
  	@post = Post.find(params[:id])
  	if current_user != @post.user
  	flash[:alert] = "編集権限がありません"
    redirect_to posts_path
	end
  end


  def update
  	@post = Post.find(params[:id])
  	if @post.update(post_params)
  		flash[:notice] = "投稿内容を編集しました"
  		redirect_to post_path(@post)
  	else
  		flash.now[:alert] = "編集に失敗しました"
  		render :edit
  	end
  end


  def destroy
  	@post = Post.find(params[:id])
  	if @post.user = current_user
  		flash[:notice] = "投稿を削除しました" if @post.destroy
  	else
  		flash[:alert] = "削除に失敗しました"
  	end
  		redirect_to root_path
  end


  private

  	def post_params
  		params.require(:post).permit(:title, :body, :genre, :catname, :image)
  	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!

  def index
    # @users = User.page(params[:page]).reverse_order
    @user_search = User.ransack(params[:q])
    @search_users = @user_search.result.page(params[:page]).reverse_order
  end

  def show
  	@user = User.find(params[:id])
    @user_follows = @user.followings
    @user_followers = @user.followers
  end

  def edit
    @user = User.find(params[:id])
    if current_user != @user
    flash[:alert] = "編集権限がありません"
    redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "ユーザー情報を編集しました"
      redirect_to user_path(@user)
    else
      flash[:alert] = "編集に失敗しました"
      redirect_to user_path(@user)
    end
  end

  def destroy
    user = current_user
    user.destroy
    redirect_to root_path
  end

  def likes
    @user = User.find(params[:id])
    @likes = Like.where(user_id: @user.id)
    @user_follows = @user.followings
    @user_followers = @user.followers
  end

  def follows
    user = User.find(params[:id])
    @users = user.followings
  end

  def followers
    user = User.find(params[:id])
    @users = user.followers
  end


private
  def user_params
    params.require(:user).permit(:name, :email, :profile_image, :introduction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nekoze</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" >
    <link rel="stylesheet" href="style.css">
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-white">
      <div class="container">
        <%= link_to root_path do %>
          <%= image_tag "/images/nekoze.png", class: "navbar-brand", size: "240x90" %>
         <% end %>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=
            "#navbar-content" aria-controls="navbar-content" aria-expend="false" aria-label=
            "Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
        <div class="collapse navbar-collapse justify-content-end" id="navbar-content">
            <ul class="nav navbar-nav ">
              <% if user_signed_in? %>
                <dl class="searchbox">
                  <%= search_form_for @search, url: posts_path do |f| %>
                    <%= f.text_field :title_or_catname_cont, placeholder: "投稿を検索..." %>
                    <%= f.submit "検索", class: 'btn btn-outline-dark btn-sm'%>
                  <% end %>
                </dl>
                <li class="nav-item">
                    <%= link_to "投稿一覧" , posts_path, class: "fas fa-images nav-link" %>
                </li>
                <li class="nav-item">
                    <%= link_to "ユーザー" , users_path, class: "fas fa-users nav-link" %>
                </li>
                <li class="nav-item">
                    <%= link_to "新規投稿", new_post_path, class: "fas fa-camera-retro nav-link" %>
                </li>
                <li class="nav-item">
                    <%= link_to "マイページ", user_path(current_user), class: "fas fa-user-circle nav-link" %>
                </li>
                <li class="nav-item">
                    <%= link_to "ログアウト",  destroy_user_session_path, method: :delete, data: {confirm: 'ログアウトしてよろしいですか？',cancel: 'やめる', commit: 'ログアウトする'}, title: '確認', class: "fas fa-sign-out-alt nav-link" %>
                </li>

              <% else %>
                <dl class="searchbox">
                  <%= search_form_for @search, url: posts_path do |f| %>
                    <%= f.text_field :title_or_catname_cont, placeholder: "投稿を検索..." %>
                    <%= f.submit "検索", class: 'btn btn-outline-dark btn-sm'%>
                  <% end %>
                </dl>
                <li class="nav-item">
                    <%= link_to "投稿一覧" , posts_path, class: "fas fa-images nav-link" %>
                </li>
                <li class="nav-item">
                <%= link_to "ログイン", new_user_session_path, class: "fas fa-sign-in-alt nav-link" %>
                </li>
                <li class="nav-item">
                <%= link_to "会員登録", new_user_registration_path, class: "fas fa-user-plus nav-link" %>
                </li>
              <% end %>
            </ul>
        </div>
      </div>
    </nav>
      <% if flash[:notice] %>
        <div class="alert alert-success">
          <%= flash[:notice] %>
        </div>
      <% end %>
      <% if flash[:alert] %>
        <div class="alert alert-danger">
          <%= flash[:alert] %>
        </div>
      <% end %>

    <%= yield %>

<script>
  $(function(){
  var num = Math.ceil(4 * Math.random());
  $('body').addClass('background' + num);
});
</script>
  </body>
</html>